"""
Core domain entities using Pydantic models.
"""

from typing import Literal

from pydantic import BaseModel, Field

from src.domain.value_objects import (
    ChangeType,
    DecisionType,
    ExecutionStatus,
    PipelinePhase,
    ReviewStatus,
)


# --- Phase 1 & 4: Retrieval ---
class RetrievalQuery(BaseModel):
    """A single retrieval query generated by the system."""

    query: str = Field(..., description="The actual search query text")
    rationale: str = Field(default="", description="Why this query is relevant")
    expected_content: str | None = Field(
        default=None, description="What kind of documents this should retrieve"
    )
    evidence: str | None = Field(
        default=None, description="Specific execution evidence triggering this query (Phase 4)"
    )
    priority: Literal["high", "medium", "low"] = Field(
        default="medium", description="Priority based on severity of issue"
    )


class CodeExample(BaseModel):
    """A code pattern retrieved from the corpus."""

    id: str
    code: str
    language: str
    explanation: str
    tags: list[str] = Field(default_factory=list)
    similarity_score: float = Field(default=0.0, description="Vector similarity score")


# --- Phase 2: Generation ---
class GeneratedCode(BaseModel):
    """Output from the generation phase."""

    code: str = Field(..., description="Complete executable code")
    explanation: str = Field(..., description="Brief explanation of approach")
    assumptions: list[str] = Field(default_factory=list, description="List of assumptions made")
    retrieved_patterns_used: list[str] = Field(
        default_factory=list, description="IDs of patterns that influenced this code"
    )
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


# --- Phase 3: Execution ---
class CoverageResult(BaseModel):
    """Code coverage metrics."""

    line_coverage: float = Field(..., ge=0.0, le=1.0)
    branch_coverage: float | None = Field(default=None, ge=0.0, le=1.0)
    uncovered_lines: list[int] = Field(default_factory=list)


class TestRunMetrics(BaseModel):
    """Unit test execution results."""
    # __test__ = False 

    passed: int = 0
    failed: int = 0
    failures: list[str] = Field(default_factory=list, description="Descriptions of failed tests")

    @property
    def total(self) -> int:
        return self.passed + self.failed


class ExecutionResult(BaseModel):
    """Result of running code in the sandbox."""

    status: ExecutionStatus
    stdout: str
    stderr: str
    exit_code: int
    runtime_trace: str | None = None
    coverage: CoverageResult | None = None
    test_results: TestRunMetrics | None = None


# --- Phase 5: Review ---
class ReviewAspect(BaseModel):
    """Evaluation of a specific aspect (correctness, security, etc.)."""

    status: ReviewStatus
    evidence: list[str] = Field(
        default_factory=list, description="Specific execution evidence citations"
    )
    findings: list[str] = Field(default_factory=list, description="List of issues or confirmations")


class Review(BaseModel):
    """Comprehensive code review."""

    correctness: ReviewAspect
    security: ReviewAspect
    robustness: ReviewAspect
    performance: ReviewAspect
    overall_quality_score: float = Field(..., ge=0.0, le=1.0)
    critical_issues: list[str] = Field(default_factory=list)
    improvement_opportunities: list[str] = Field(default_factory=list)
    optimization_score: float = Field(default=0.5, ge=0.0, le=1.0, description="How optimized the code is (1.0 = fully optimized)")
    optimization_gaps: list[str] = Field(default_factory=list, description="Areas where code can be further optimized")


# --- Phase 6: Decision & Repair ---
class RepairStrategy(BaseModel):
    """Plan for repairing code if decision is CONTINUE."""

    lines_to_modify: list[int]
    patterns_to_apply: list[str]
    validation_criteria: list[str]
    
class DecisionResult(BaseModel):
    """Final decision for the iteration."""

    decision: DecisionType
    rationale: str
    next_iteration_focus: str | None = None
    repair_strategy: RepairStrategy | None = None


class RepairChange(BaseModel):
    """Documentation of a specific change made during repair."""

    line_range: str
    change_type: ChangeType
    description: str
    retrieved_pattern_applied: str | None = None
    addresses_evidence: str | None = None


# --- Pipeline State ---
class PipelineState(BaseModel):
    """State of the pipeline across iterations."""

    run_id: str
    user_query: str
    language: str
    max_iterations: int
    current_iteration: int = 1
    current_phase: PipelinePhase = PipelinePhase.RETRIEVAL
    
    # History
    history_retrieval: list[list[RetrievalQuery]] = Field(default_factory=list)
    history_code: list[GeneratedCode] = Field(default_factory=list)
    history_execution: list[ExecutionResult] = Field(default_factory=list)
    history_review: list[Review] = Field(default_factory=list)
    
    # Current context
    current_context_docs: list[CodeExample] = Field(default_factory=list)

    @property
    def last_code(self) -> str | None:
        """Get the most recently generated code."""
        if not self.history_code:
            return None
        return self.history_code[-1].code

    @property
    def last_execution(self) -> ExecutionResult | None:
        """Get the most recent execution result."""
        if not self.history_execution:
            return None
        return self.history_execution[-1]
        
class IterationDetail(BaseModel):
    """Details of a single iteration in the pipeline."""
    
    iteration_number: int = Field(..., description="The iteration number (1-based)")
    phase_results: dict[str, dict] = Field(
        default_factory=dict,
        description="Results from each phase in this iteration"
    )
    retrieval_count: int = Field(default=0, description="Number of documents retrieved")
    code_generated: bool = Field(default=False, description="Whether code was generated")
    execution_status: str | None = Field(default=None, description="Execution result status")
    tests_passed: int = Field(default=0, description="Tests passed in this iteration")
    tests_failed: int = Field(default=0, description="Tests failed in this iteration")
    coverage: float = Field(default=0.0, description="Coverage achieved this iteration")
    critical_issues: list[str] = Field(default_factory=list, description="Critical issues found")
    decision: str | None = Field(default=None, description="Decision made (CONTINUE/TERMINATE)")
    duration_ms: int = Field(default=0, description="Time taken for this iteration in ms")


class GenerateResponse(BaseModel):
    """Response model for code generation."""

    code: str = Field(..., description="Generated code")
    explanation: str = Field(..., description="Explanation of the solution")
    iterations: int = Field(..., description="Number of iterations taken")
    status: Literal["success", "partial", "failed", "pending"] = Field(
        ..., description="Final status of generation"
    )
    coverage: float | None = Field(default=None, description="Test coverage if available")
    tests_passed: int | None = Field(default=None, description="Number of tests passed")
    tests_failed: int | None = Field(default=None, description="Number of tests failed")
    tests_total: int | None = Field(default=None, description="Total number of tests executed")
    
    # Detailed iteration history for visualization
    iteration_details: list[IterationDetail] = Field(
        default_factory=list,
        description="Detailed information about each iteration"
    )
    total_duration_ms: int = Field(default=0, description="Total pipeline execution time in ms")
    retrieved_patterns: list[str] = Field(
        default_factory=list,
        description="IDs of all patterns retrieved across iterations"
    )